server:
  port: 8080

routes:
  client-service-url: ${CLIENT_SERVICE_URL:http://localhost:8081}
  vehicle-service-url: ${VEHICLE_SERVICE_URL:http://localhost:8082}
  facturation-service-url: ${FACTURATION_SERVICE_URL:http://localhost:8083}
  maintenance-service-url: ${MAINTENANCE_SERVICE_URL:http://localhost:8084}
  notification-service-url: ${NOTIFICATION_SERVICE_URL:http://localhost:8085}

